init:
  - git config --global core.autocrlf input
environment:
  COVERALLS_REPO_TOKEN:
    secure: 1dnzq+xYoQT5eCrmH7IE/npTL0kpQ3IyeMYSWK1NvVuAXX6NNbhvO5eP1SCr7q/X
build_script:
  - cmd: build.cmd
  - cmd: build.cmd Coverage
  - cmd: set
  - cmd: packages\coveralls.net\csmacnz.Coveralls.exe --opencover -i coverage.xml --repoToken %COVERALLS_REPO_TOKEN% --useRelativePaths --commitId %APPVEYOR_REPO_COMMIT% --commitBranch "%APPVEYOR_REPO_BRANCH%" --commitAuthor "%APPVEYOR_REPO_COMMIT_AUTHOR%" --commitEmail %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL% --commitMessage "%APPVEYOR_REPO_COMMIT_MESSAGE%" --jobId %APPVEYOR_JOB_ID%
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
