init:
  - git config --global core.autocrlf input
environment:
  COVERALLS_REPO_TOKEN:
    secure: 1dnzq+xYoQT5eCrmH7IE/npTL0kpQ3IyeMYSWK1NvVuAXX6NNbhvO5eP1SCr7q/X
build_script:
  - cmd: build.cmd
  - cmd: build.cmd Coverage
test: off
version: 0.3.3.{build}
artifacts:
  - path: bin
    name: bin
